-- Disable RLS for development - run this in Supabase SQL Editor
-- This allows full access during development

ALTER TABLE teachers DISABLE ROW LEVEL SECURITY;
ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_games DISABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_levels DISABLE ROW LEVEL SECURITY;
ALTER TABLE question_bank DISABLE ROW LEVEL SECURITY;
ALTER TABLE level_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_answers DISABLE ROW LEVEL SECURITY; 